#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles



PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=37        \
                 blur_radius=30   \
                 position=top     \
                 sticky=off       \
                 padding_left=20  \
                 padding_right=20 \
                 color=$BAR_COLOR \
                 hotload=true

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="Hack Nerd Font:Bold:17.0"  \
                     icon.color=$WHITE                 \
                     label.font="Hack Nerd Font:Bold:14.0" \
                     label.color=$WHITE                \
                     padding_left=12                   \
                     padding_right=12                  \


##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.

SPACE_SIDS=(1 2 3 4 5 6 7 8 9 10)

for sid in "${SPACE_SIDS[@]}"
do
  sketchybar --add space space.$sid left                                 \
             --set space.$sid space=$sid                                 \
                              icon=$sid                                  \
                              label.font="Hack Nerd Font:Bold:16.0" \
                              label.padding_right=10                     \
                              label.y_offset=-1                          \
                              script="$PLUGIN_DIR/space.sh" \
                              update_freq=5
done



##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item front_app left \
           --set front_app       background.drawing=off \
                                 icon.color=$WHITE \
                                 icon.font="Hack Nerd Font:Bold:16.0" \
                                 label.color=$WHITE \
                                 script="$PLUGIN_DIR/front_app.sh"            \
           --subscribe front_app front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
           --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh"

# --add item volume right \
# --set volume script="$PLUGIN_DIR/volume.sh" \
# --subscribe volume volume_change \
# --add item battery right \
# --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
# --subscribe battery system_woke power_source_change

sketchybar --add item cpu right \
           --set cpu icon="" \
                     update_freq=10 \
                     script="$PLUGIN_DIR/cpu.sh"

sketchybar --add item volume right \
           --set volume icon="􀊤" \
                     icon.padding_right=8 \
                     icon.y_offset=1 \
                     label.padding_left=8 \
                     update_freq=5 \
                     script="$PLUGIN_DIR/volume.sh" \
                     click_script="$PLUGIN_DIR/volume_popup.sh" \
           --subscribe volume volume_change

sketchybar --add item brightness right \
           --set brightness icon="􀆮" \
                     icon.padding_right=8 \
                     icon.y_offset=1 \
                     label.padding_left=8 \
                     update_freq=5 \
                     script="$PLUGIN_DIR/brightness.sh" \
                     click_script="$PLUGIN_DIR/brightness_popup.sh"

sketchybar --add item media center \
           --set media label.color=$ACCENT_COLOR \
                       label.max_chars=50 \
                       label.padding_left=30 \
                       label.padding_right=30 \
                       icon.padding_left=30 \
                       icon.padding_right=30 \
                       align=center \
                       scroll_texts=on \
                       label.scroll_duration=300 \
                       label.scroll_pause=0 \
                       icon= \
                       icon.color=$ACCENT_COLOR   \
                       background.drawing=off \
                       script="$PLUGIN_DIR/media.sh" \
                       click_script="$PLUGIN_DIR/media_popup.sh" \
                       update_freq=5

# sketchybar --add item calendar right \
#            --set calendar icon=  \
#            --set calendar label="$(date +'%a %d %b %I:%M %p')"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
